// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz-ojMYDM_JxFDZzY4WfM2R6Pi2fRNurA',
    appId: '1:633541711215:android:b41dcd7a95cac36708c49a',
    messagingSenderId: '633541711215',
    projectId: 'maseerah-68b24',
    databaseURL: 'https://maseerah-68b24-default-rtdb.firebaseio.com',
    storageBucket: 'maseerah-68b24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqnkK91-rm3z8yR4eLOgo3q4TE7mth71s',
    appId: '1:633541711215:ios:2948f7635e65166e08c49a',
    messagingSenderId: '633541711215',
    projectId: 'maseerah-68b24',
    databaseURL: 'https://maseerah-68b24-default-rtdb.firebaseio.com',
    storageBucket: 'maseerah-68b24.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpYZXgiqFHeW-QOBzxVCpJXJwxlebA5kI',
    appId: '1:633541711215:web:d5149bba2403744e08c49a',
    messagingSenderId: '633541711215',
    projectId: 'maseerah-68b24',
    authDomain: 'maseerah-68b24.firebaseapp.com',
    databaseURL: 'https://maseerah-68b24-default-rtdb.firebaseio.com',
    storageBucket: 'maseerah-68b24.firebasestorage.app',
    measurementId: 'G-TVWMHB3P34',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqnkK91-rm3z8yR4eLOgo3q4TE7mth71s',
    appId: '1:633541711215:ios:2948f7635e65166e08c49a',
    messagingSenderId: '633541711215',
    projectId: 'maseerah-68b24',
    databaseURL: 'https://maseerah-68b24-default-rtdb.firebaseio.com',
    storageBucket: 'maseerah-68b24.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpYZXgiqFHeW-QOBzxVCpJXJwxlebA5kI',
    appId: '1:633541711215:web:7e80d6ad6f72547f08c49a',
    messagingSenderId: '633541711215',
    projectId: 'maseerah-68b24',
    authDomain: 'maseerah-68b24.firebaseapp.com',
    databaseURL: 'https://maseerah-68b24-default-rtdb.firebaseio.com',
    storageBucket: 'maseerah-68b24.firebasestorage.app',
    measurementId: 'G-E8L179539Z',
  );

}